version: "3.9"

services:
  postgres:
    image: postgis/postgis:13-master
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build: ./todo-backend/
    ports:
      - 4000:4000
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    depends_on:
      - postgres

  frontend:
    build: ./todo-frontend/
    ports:
      - 5000:5000
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./templates:/etc/nginx/templates
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST}
      - BACKEND_HOST=${BACKEND_HOST}
      - FRONTEND_PROXY=${FRONTEND_PROXY}
      - BACKEND_PROXY=${BACKEND_PROXY}

      - FRONTEND_CERT=${FRONTEND_CERT}
      - FRONTEND_KEY=${FRONTEND_KEY}
      - BACKEND_CERT=${BACKEND_CERT}
      - BACKEND_KEY=${BACKEND_KEY}
    command: sh -c "mkdir -p /etc/nginx/ssl/${BACKEND_HOST}
      && echo '$BACKEND_CERT' > /etc/nginx/ssl/${BACKEND_HOST}/cert.pem
      && echo '$BACKEND_KEY' > /etc/nginx/ssl/${BACKEND_HOST}/private.pem
      && mkdir -p /etc/nginx/ssl/${FRONTEND_HOST}
      && echo '$FRONTEND_CERT' > /etc/nginx/ssl/${FRONTEND_HOST}/cert.pem
      && echo '$FRONTEND_KEY' > /etc/nginx/ssl/${FRONTEND_HOST}/private.pem
      && envsubst '$$FRONTEND_HOST $$BACKEND_HOST $$FRONTEND_PROXY $$BACKEND_PROXY' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;' && tail -f /dev/null"
    depends_on:
      - frontend
      - backend
